name: plantmon
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - boto3
  - docformatter
  - flask
  - gunicorn
  - libgpiod
  - pandas
  - pylint
  - python
  - seaborn
  - pip:
      - awscrt
      - binho-host-adapter
      - emoji
      - gpiod
      - halo
      - lgpio
      - log-symbols
      - pyftdi
      - pyserial
      - pyusb
      - rpi-gpio
      - rpi-lgpio
      - spinners
      - sysv-ipc
      - termcolor
