name: plantmon
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - boto3
  - docformatter
  - flask
  - gunicorn
  - libgpiod
  - pandas
  - pylint
  - python
  - seaborn
  - pip:
      - awscrt
      - emoji
      - Frozen-Flask
      - halo
      - log-symbols
      - spinners
      - termcolor
